name: Paper-Kotlin-Template
version: 1.0.0
main: hello.PluginTemplate
api-version: '1.20'
authors: [ The Flyte Team ]
description: Paper Plugin Template written in Kotlin.
website: https://flyte.gg
commands:
  rank:
  spawn:
  repair:
  money:
  pay:
  home:
  realm:
  build:
  adminmenu:
  click:
  remove:
  realms:
  org: