CREATE TABLE IF NOT EXISTS homes (
  homeid BIGINT AUTO_INCREMENT PRIMARY KEY,
  uuid VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  location VARCHAR(255) NOT NULL,
  player VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS mcplayer (
  uuid VARCHAR(255) PRIMARY KEY,
  rang VARCHAR(255) NOT NULL,
  geld INT NOT NULL
);


CREATE TABLE IF NOT EXISTS buildrealmallowed (
  id INT AUTO_INCREMENT PRIMARY KEY,
  ownerUUID VARCHAR(255) NOT NULL
  );
